version: "3.3"

services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    init: true
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

